name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v3

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:latest
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: simple_bank
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go
    
    - name: Checkout code into Go module directory
      uses: actions/checkout@v2
    
    - name: Run migration
      run: make migrate_up

    - name: Test # app will be built on running test functions, hence no need of Build step
      run: make test # since we already have this covered in the Makefile as a target
