name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
      id: go
    
    - name: Checkout code into Go module directory
      uses: actions/checkout@v2

    - name: Test # app will be built on running test functions, hence no need of Build step
      run: make test # since we already have this covered in the Makefile as a target
